version: '3'
services:
  db:
    container_name: music-center-db
    image: postgres:11.2
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=db
    ports:
      - '50432:5432'
    volumes:
    - ./infra/db:/var/lib/postgresql/data
    